/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzeria;

/**
 * Pokazuje podstawowe informacje o Człowieku.
 * @author Marcin
 */
public class CzlowiekInfoJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CzlowiekInfoJFrame
     */
    private Czlowiek czlowiek;
    private Pizzeria pizzeria;
    public CzlowiekInfoJFrame() {
        initComponents();
    }
    public CzlowiekInfoJFrame(Pizzeria p, Czlowiek c) {
        initComponents();
        czlowiek = c;
        pizzeria = p;
        setInfo();
    }
    
    public void setInfo(){
        imieL.setText(czlowiek.getImie());
        nazwiskoL.setText(czlowiek.getNazwisko());
        peselL.setText(czlowiek.getPesel());
        typL.setText(czlowiek.getClass().getSimpleName());
        xL.setText(Integer.toString(czlowiek.getPolozenie().getX()));
        yL.setText(Integer.toString(czlowiek.getPolozenie().getY()));
        pojazdCB.setVisible(false);
        if(czlowiek instanceof Klient){
            Klient k = (Klient) czlowiek;
            extraL3.setText("Tel. : ");
            extraVL3.setText(k.getTelefon());
            extraL4.setText("Mail. : ");
            extraVL4.setText(k.getMail());
            powrotB.setVisible(false);
        }
        if(czlowiek instanceof KlientStaly){
            KlientStaly k = (KlientStaly) czlowiek;
            extraL.setText("P.Loj. : ");
            extraVL.setText(Float.toString(k.getpLojal()));
        }
            if(czlowiek instanceof KlientFirmowy){
            KlientFirmowy k = (KlientFirmowy) czlowiek;
            extraL.setText("Koresp. : ");
            extraVL.setText(k.getAdresKoresp());
            extraL1.setText("REGON : ");
            extraVL1.setText(k.getRegon());
            extraL2.setText("Konto : ");
            extraVL2.setText(k.getNrKontaBank());
        }
        if(czlowiek instanceof Dostawca){
            pojazdCB.setVisible(true);
            Dostawca d = (Dostawca) czlowiek;
            pojazdL.setText(d.getPojazd().getClass().getName());
            paliwoL.setText("Paliwo : " + Float.toString(d.getPojazd().getPaliwo()) + "/" +
                               Float.toString(d.getPojazd().getPojemoscBaku()));
            pojazdCB.removeAllItems();
            if(d.getUprawnieniaPojazd() == Dostawca.UprPojazd.Wszystkie){
                pojazdCB.addItem("Samochód");
                pojazdCB.addItem("Skuter");
                if((d.getPojazd() instanceof Skuter) || ((d.getPojazd() instanceof Samochod) &&
                        d.isZmienPojazd()))
                    pojazdCB.setSelectedIndex(1);
            }
            else if(d.getUprawnieniaPojazd() == Dostawca.UprPojazd.Skuter){
                pojazdCB.addItem("Skuter");
            }
            else
               pojazdCB.addItem("Samochód"); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imieL = new javax.swing.JLabel();
        nazwiskoL = new javax.swing.JLabel();
        peselL = new javax.swing.JLabel();
        typL = new javax.swing.JLabel();
        xL = new javax.swing.JLabel();
        yL = new javax.swing.JLabel();
        refreshB = new javax.swing.JButton();
        pojazdL = new javax.swing.JLabel();
        paliwoL = new javax.swing.JLabel();
        usunB = new javax.swing.JButton();
        pojazdCB = new javax.swing.JComboBox<>();
        extraL = new javax.swing.JLabel();
        extraVL = new javax.swing.JLabel();
        extraL1 = new javax.swing.JLabel();
        extraVL1 = new javax.swing.JLabel();
        extraL2 = new javax.swing.JLabel();
        extraVL2 = new javax.swing.JLabel();
        extraL3 = new javax.swing.JLabel();
        extraVL3 = new javax.swing.JLabel();
        extraL4 = new javax.swing.JLabel();
        extraVL4 = new javax.swing.JLabel();
        powrotB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        imieL.setText("imię");

        nazwiskoL.setText("nazwisko");

        peselL.setText("PESEL");

        typL.setText("Typ");
        typL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        xL.setText("x");

        yL.setText("y");

        refreshB.setText("Odśwież");
        refreshB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshBMouseClicked(evt);
            }
        });

        usunB.setText("Usuń");
        usunB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usunBMouseClicked(evt);
            }
        });

        pojazdCB.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                pojazdCBPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        powrotB.setText("Powrót");
        powrotB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                powrotBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nazwiskoL, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(peselL, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(xL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(extraL3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(extraVL3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(extraL4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(extraVL4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(typL, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(imieL, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(powrotB)
                                    .addComponent(usunB))))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(extraL1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(extraVL1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(extraL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(extraVL))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(extraL2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(extraVL2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paliwoL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pojazdCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pojazdL, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(refreshB)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typL)
                    .addComponent(pojazdL)
                    .addComponent(pojazdCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usunB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(imieL)
                            .addComponent(powrotB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nazwiskoL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peselL)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xL)
                            .addComponent(yL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(extraL3)
                            .addComponent(extraVL3))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(extraL4)
                            .addComponent(extraVL4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(refreshB))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paliwoL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(extraL)
                            .addComponent(extraVL))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(extraL1)
                            .addComponent(extraVL1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(extraL2)
                            .addComponent(extraVL2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void refreshBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshBMouseClicked
        // TODO add your handling code here:
        setInfo();
    }//GEN-LAST:event_refreshBMouseClicked

    private void usunBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usunBMouseClicked
        // TODO add your handling code here:
        if(czlowiek instanceof Klient){
            pizzeria.getKlientL().remove(czlowiek.getImie() + " " + czlowiek.getNazwisko());
            czlowiek.setZyj(false);
        }
        else if(czlowiek instanceof Dostawca){
            System.out.println("Dostawca zostanie usunięty po dostarczeniu obecnego zamówienia.");
            Dostawca d = (Dostawca) czlowiek;
            d.setZwolniony(true);
           // pizzeria.getDostawcaL().remove(czlowiek.getImie() + " " + czlowiek.getNazwisko());
        }
        
        pizzeria.getMapa().repaint();
        this.setVisible(false);
    }//GEN-LAST:event_usunBMouseClicked

    private void pojazdCBPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_pojazdCBPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        zmienPojazd();
    }//GEN-LAST:event_pojazdCBPopupMenuWillBecomeInvisible

    private void powrotBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_powrotBMouseClicked
        // TODO add your handling code here:
        if(czlowiek instanceof Dostawca){
            System.out.println("Dostawca wróci po dostarczeniu obecnego zamówienia.");
            Dostawca d = (Dostawca) czlowiek;
            d.setAwaryjnyPow(true);
            this.setVisible(false);
           // pizzeria.getDostawcaL().remove(czlowiek.getImie() + " " + czlowiek.getNazwisko());
        }
    }//GEN-LAST:event_powrotBMouseClicked
    public void zmienPojazd(){
        Dostawca d = (Dostawca) czlowiek;
        if("Samochód".equals(pojazdCB.getSelectedItem().toString()) && (d.getPojazd() instanceof Skuter))
            d.setZmienPojazd(true);
        else if("Samochód".equals(pojazdCB.getSelectedItem().toString()) && (d.getPojazd() instanceof Samochod))
            d.setZmienPojazd(false);
        else if("Skuter".equals(pojazdCB.getSelectedItem().toString()) && (d.getPojazd() instanceof Samochod))
            d.setZmienPojazd(true);
        else
            d.setZmienPojazd(false);
        System.out.println("Zmiana pojazdu dla " + d.getImie() + 
                " nastąpi przy najbiższym pobycie w pizzerii.");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CzlowiekInfoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CzlowiekInfoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CzlowiekInfoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CzlowiekInfoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CzlowiekInfoJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel extraL;
    private javax.swing.JLabel extraL1;
    private javax.swing.JLabel extraL2;
    private javax.swing.JLabel extraL3;
    private javax.swing.JLabel extraL4;
    private javax.swing.JLabel extraVL;
    private javax.swing.JLabel extraVL1;
    private javax.swing.JLabel extraVL2;
    private javax.swing.JLabel extraVL3;
    private javax.swing.JLabel extraVL4;
    private javax.swing.JLabel imieL;
    private javax.swing.JLabel nazwiskoL;
    private javax.swing.JLabel paliwoL;
    private javax.swing.JLabel peselL;
    private javax.swing.JComboBox<String> pojazdCB;
    private javax.swing.JLabel pojazdL;
    private javax.swing.JButton powrotB;
    private javax.swing.JButton refreshB;
    private javax.swing.JLabel typL;
    private javax.swing.JButton usunB;
    private javax.swing.JLabel xL;
    private javax.swing.JLabel yL;
    // End of variables declaration//GEN-END:variables
}
