/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzeria;

import java.awt.BorderLayout;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 * Spis dań oraz możliwośc dodawania ich.
 * @author Marcin
 */
public class menuJFrame extends javax.swing.JFrame {
    private Pizzeria pizzeria;
    DefaultListModel listModel = new DefaultListModel();
    JList listaL = new JList(listModel);
    JScrollPane listaPane = new JScrollPane(listaL);
    ListSelectionListener lsl;
    
    public void setPizzeria(Pizzeria pizzeria) {
        this.pizzeria = pizzeria;
    }
    
    /**
     * Creates new form menuJFrame
     */
    public menuJFrame() {
        initComponents();
        lsl = new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent arg0) {
                if (!arg0.getValueIsAdjusting()) {
                    Produkt p = pizzeria.getMenu().get(listaL.getSelectedValue());
                  cenaL.setText(Float.toString(p.getCena()));
                  rodzajL.setText(p.getClass().getSimpleName());
                  czasL.setText(Integer.toString(p.getCzasPrzygot()));
                  skladnikiL.setText(p.getSkladniki());
                  porcjeL.setText(Boolean.toString(p.isPorcjowany()));
                }
            }
        };
        listaL.addListSelectionListener(lsl);
        listaPane.setBounds(5, 5, 140, 200);
        add(listaPane);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        nazwaT = new javax.swing.JTextField();
        cenaT = new javax.swing.JTextField();
        czasT = new javax.swing.JTextField();
        rodzajC = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cenaL = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        skladnikiL = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        czasL = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rodzajL = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        porcjeL = new javax.swing.JLabel();
        skladnikiT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        porcjowanyCB = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setText("Dodaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cenaT.setText("10");

        czasT.setText("5");

        rodzajC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pizza", "Sos", "Zupa", "Napój", "Deser" }));

        jLabel1.setText("Nazwa");

        jLabel2.setText("Cena");

        jLabel3.setText("Czas przyg.");

        jLabel4.setText("Cena :");

        cenaL.setText("0");

        jLabel5.setText("Składniki :");

        skladnikiL.setText("Ser, Pomidory...");

        jLabel7.setText("Czas p. :");

        czasL.setText("10");

        jLabel9.setText("Rodzaj :");

        rodzajL.setText("Pizza");

        jLabel11.setText("Porcje :");

        porcjeL.setText("Mała, średnia...");

        skladnikiT.setText("-");

        jLabel6.setText("Składniki");

        porcjowanyCB.setText("Rozm. Porcji?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nazwaT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addGap(48, 48, 48)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cenaT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(czasT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(skladnikiT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rodzajC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cenaL))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(skladnikiL))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(czasL))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rodzajL))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(porcjeL)))
                                .addGap(0, 106, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(porcjowanyCB)))))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rodzajL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cenaL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(skladnikiL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(czasL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(porcjeL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazwaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cenaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(czasT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(skladnikiT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rodzajC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(porcjowanyCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            listaL.removeListSelectionListener(lsl);
            boolean porcje = false;
            if(porcjowanyCB.isSelected())
                porcje = true;
            if("".equals(nazwaT.getText()) || "".equals(skladnikiT.getText()) || 
                    "".equals(cenaT.getText()) || "".equals(czasT.getText()))
                throw new MyException("Podaj wszystkie dane!");
            Produkt p;
            if(rodzajC.getSelectedItem() == "Pizza")
                p = new Pizza(nazwaT.getText(), Float.parseFloat(cenaT.getText()), 
                    Integer.parseInt(czasT.getText()),skladnikiT.getText(), porcje);
            else if(rodzajC.getSelectedItem() == "Deser")
                p = new Deser(nazwaT.getText(), Float.parseFloat(cenaT.getText()), 
                    Integer.parseInt(czasT.getText()),skladnikiT.getText(), porcje);
            else if(rodzajC.getSelectedItem() == "Zupa")
                p = new Zupa(nazwaT.getText(), Float.parseFloat(cenaT.getText()), 
                    Integer.parseInt(czasT.getText()),skladnikiT.getText(), porcje);
            else if(rodzajC.getSelectedItem() == "Napój")
                p = new Napoj(nazwaT.getText(), Float.parseFloat(cenaT.getText()), 
                    Integer.parseInt(czasT.getText()),skladnikiT.getText(), porcje);
            else if(rodzajC.getSelectedItem() == "Sos")
                p = new Sos(nazwaT.getText(), Float.parseFloat(cenaT.getText()), 
                    Integer.parseInt(czasT.getText()),skladnikiT.getText(), porcje);
            else
                p = new Produkt(nazwaT.getText(), Float.parseFloat(cenaT.getText()), 
                    Integer.parseInt(czasT.getText()),skladnikiT.getText(), porcje);
            if(pizzeria.getMenu().get(p.getNazwa()) == null)
                pizzeria.getMenu().put(p.getNazwa(),p);
            else 
                throw new MyException("Produkt o tej nazwie już istnieje.");
            odswiezListe();
            Random generator = new Random();
            nazwaT.setText("Produkt"+Integer.toString(generator.nextInt(1000)));
            //this.setVisible(false);
            listaL.addListSelectionListener(lsl);
        }
        catch(MyException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void odswiezListe(){
        listModel.clear();
        HashMap<String, Produkt> selects = pizzeria.getMenu();
        for(Map.Entry<String, Produkt> entry : selects.entrySet()) {
            String key = entry.getKey();
            Produkt value = entry.getValue();
            listModel.addElement(value.getNazwa());
        }   
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Random generator = new Random();
        odswiezListe();
        nazwaT.setText("Produkt"+Integer.toString(generator.nextInt(1000)));
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cenaL;
    private javax.swing.JTextField cenaT;
    private javax.swing.JLabel czasL;
    private javax.swing.JTextField czasT;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nazwaT;
    private javax.swing.JLabel porcjeL;
    private javax.swing.JCheckBox porcjowanyCB;
    private javax.swing.JComboBox<String> rodzajC;
    private javax.swing.JLabel rodzajL;
    private javax.swing.JLabel skladnikiL;
    private javax.swing.JTextField skladnikiT;
    // End of variables declaration//GEN-END:variables
}
