/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzeria;

import java.awt.event.ActionListener;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JToggleButton;

/**
 * Okno informacyjne.
 * @author Marcin
 */
public class PizzeriaJFrame extends JFrame {
    
    private Pizzeria pizzeria = new Pizzeria();
    public void setPizzeria(Pizzeria pizzeria) {
        this.pizzeria = pizzeria;
    }
    public PizzeriaJFrame(Pizzeria pizzeria) {
        this.pizzeria = pizzeria;
        initComponents();
        //this.getGraphics().clearRect(0, 0, 300, 300);
    }
        public PizzeriaJFrame() {
        initComponents();
        //this.getGraphics().clearRect(0, 0, 300, 300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        zamowB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        kasaL = new javax.swing.JLabel();
        zapiszB = new javax.swing.JButton();
        wczytajB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Dodaj Klienta");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jToggleButton1.setText("Dodaj Dostawcę");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });

        jToggleButton2.setText("Menu");
        jToggleButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton2MouseClicked(evt);
            }
        });

        zamowB.setText("Zamów");
        zamowB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zamowBMouseClicked(evt);
            }
        });
        zamowB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamowBActionPerformed(evt);
            }
        });

        jLabel1.setText("Skarbonka :");

        kasaL.setText("0");

        zapiszB.setText("Zapisz");
        zapiszB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zapiszBMouseClicked(evt);
            }
        });

        wczytajB.setText("Wczytaj");
        wczytajB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wczytajBMouseClicked(evt);
            }
        });
        wczytajB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wczytajBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(zamowB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kasaL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 412, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(zapiszB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(wczytajB, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kasaL)
                    .addComponent(zapiszB, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wczytajB, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 348, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2)
                    .addComponent(zamowB))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        DodajKlientaJFrame dkJF = new DodajKlientaJFrame();
        dkJF.setPizzeria(pizzeria);
        dkJF.setVisible(true);
        dkJF.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        DodajDostawceJFrame ddJF = new DodajDostawceJFrame();
        ddJF.setPizzeria(pizzeria);
        ddJF.setVisible(true);
        ddJF.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jToggleButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton2MouseClicked
        menuJFrame mF = new menuJFrame();
        mF.setPizzeria(pizzeria);
        mF.setVisible(true);
        mF.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jToggleButton2MouseClicked

    private void zamowBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamowBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zamowBActionPerformed

    private void zamowBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zamowBMouseClicked
        // TODO add your handling code here:
        ZamowJFrame zF = new ZamowJFrame();
        zF.setPizzeria(pizzeria);
        zF.setVisible(true);
        zF.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_zamowBMouseClicked

    private void zapiszBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zapiszBMouseClicked
        // TODO add your handling code here:
        pizzeria.zapiszStan();
    }//GEN-LAST:event_zapiszBMouseClicked

    private void wczytajBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wczytajBMouseClicked
        // TODO add your handling code here:
          pizzeria.wczytajStan();
    }//GEN-LAST:event_wczytajBMouseClicked

    private void wczytajBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wczytajBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wczytajBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzeriaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzeriaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzeriaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzeriaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizzeriaJFrame().setVisible(true);
            }
        });
    }
    
    public void refresh(){
        kasaL.setText(Float.toString(pizzeria.getKasa()));
    }
    
    public JButton getjButton1() {
        return jButton1;
    }

    public JToggleButton getjToggleButton1() {
        return jToggleButton1;
    }

    public JLabel getKasaL() {
        return kasaL;
    }

    public JButton getWczytajB() {
        return wczytajB;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel kasaL;
    private javax.swing.JButton wczytajB;
    private javax.swing.JButton zamowB;
    private javax.swing.JButton zapiszB;
    // End of variables declaration//GEN-END:variables
}
